// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: adoption.proto

package adoption

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ApplicationStatus int32

const (
	ApplicationStatus_APPLICATION_STATUS_UNSPECIFIED ApplicationStatus = 0
	ApplicationStatus_PENDING_REVIEW                 ApplicationStatus = 1
	ApplicationStatus_APPROVED                       ApplicationStatus = 2
	ApplicationStatus_REJECTED                       ApplicationStatus = 3
	ApplicationStatus_CANCELLED_BY_USER              ApplicationStatus = 5
)

// Enum value maps for ApplicationStatus.
var (
	ApplicationStatus_name = map[int32]string{
		0: "APPLICATION_STATUS_UNSPECIFIED",
		1: "PENDING_REVIEW",
		2: "APPROVED",
		3: "REJECTED",
		5: "CANCELLED_BY_USER",
	}
	ApplicationStatus_value = map[string]int32{
		"APPLICATION_STATUS_UNSPECIFIED": 0,
		"PENDING_REVIEW":                 1,
		"APPROVED":                       2,
		"REJECTED":                       3,
		"CANCELLED_BY_USER":              5,
	}
)

func (x ApplicationStatus) Enum() *ApplicationStatus {
	p := new(ApplicationStatus)
	*p = x
	return p
}

func (x ApplicationStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ApplicationStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_adoption_proto_enumTypes[0].Descriptor()
}

func (ApplicationStatus) Type() protoreflect.EnumType {
	return &file_adoption_proto_enumTypes[0]
}

func (x ApplicationStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ApplicationStatus.Descriptor instead.
func (ApplicationStatus) EnumDescriptor() ([]byte, []int) {
	return file_adoption_proto_rawDescGZIP(), []int{0}
}

type AdoptionApplication struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId           string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PetId            string                 `protobuf:"bytes,3,opt,name=pet_id,json=petId,proto3" json:"pet_id,omitempty"`
	Status           ApplicationStatus      `protobuf:"varint,4,opt,name=status,proto3,enum=adoption.ApplicationStatus" json:"status,omitempty"`
	ApplicationNotes string                 `protobuf:"bytes,5,opt,name=application_notes,json=applicationNotes,proto3" json:"application_notes,omitempty"`
	ReviewNotes      string                 `protobuf:"bytes,6,opt,name=review_notes,json=reviewNotes,proto3" json:"review_notes,omitempty"`
	CreatedAt        *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // Or use string if preferred
	UpdatedAt        *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"` // Or use string
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AdoptionApplication) Reset() {
	*x = AdoptionApplication{}
	mi := &file_adoption_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdoptionApplication) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdoptionApplication) ProtoMessage() {}

func (x *AdoptionApplication) ProtoReflect() protoreflect.Message {
	mi := &file_adoption_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdoptionApplication.ProtoReflect.Descriptor instead.
func (*AdoptionApplication) Descriptor() ([]byte, []int) {
	return file_adoption_proto_rawDescGZIP(), []int{0}
}

func (x *AdoptionApplication) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AdoptionApplication) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AdoptionApplication) GetPetId() string {
	if x != nil {
		return x.PetId
	}
	return ""
}

func (x *AdoptionApplication) GetStatus() ApplicationStatus {
	if x != nil {
		return x.Status
	}
	return ApplicationStatus_APPLICATION_STATUS_UNSPECIFIED
}

func (x *AdoptionApplication) GetApplicationNotes() string {
	if x != nil {
		return x.ApplicationNotes
	}
	return ""
}

func (x *AdoptionApplication) GetReviewNotes() string {
	if x != nil {
		return x.ReviewNotes
	}
	return ""
}

func (x *AdoptionApplication) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *AdoptionApplication) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateAdoptionApplicationRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UserId           string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PetId            string                 `protobuf:"bytes,2,opt,name=pet_id,json=petId,proto3" json:"pet_id,omitempty"`
	ApplicationNotes string                 `protobuf:"bytes,3,opt,name=application_notes,json=applicationNotes,proto3" json:"application_notes,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateAdoptionApplicationRequest) Reset() {
	*x = CreateAdoptionApplicationRequest{}
	mi := &file_adoption_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAdoptionApplicationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAdoptionApplicationRequest) ProtoMessage() {}

func (x *CreateAdoptionApplicationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_adoption_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAdoptionApplicationRequest.ProtoReflect.Descriptor instead.
func (*CreateAdoptionApplicationRequest) Descriptor() ([]byte, []int) {
	return file_adoption_proto_rawDescGZIP(), []int{1}
}

func (x *CreateAdoptionApplicationRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateAdoptionApplicationRequest) GetPetId() string {
	if x != nil {
		return x.PetId
	}
	return ""
}

func (x *CreateAdoptionApplicationRequest) GetApplicationNotes() string {
	if x != nil {
		return x.ApplicationNotes
	}
	return ""
}

type GetAdoptionApplicationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApplicationId string                 `protobuf:"bytes,1,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAdoptionApplicationRequest) Reset() {
	*x = GetAdoptionApplicationRequest{}
	mi := &file_adoption_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAdoptionApplicationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAdoptionApplicationRequest) ProtoMessage() {}

func (x *GetAdoptionApplicationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_adoption_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAdoptionApplicationRequest.ProtoReflect.Descriptor instead.
func (*GetAdoptionApplicationRequest) Descriptor() ([]byte, []int) {
	return file_adoption_proto_rawDescGZIP(), []int{2}
}

func (x *GetAdoptionApplicationRequest) GetApplicationId() string {
	if x != nil {
		return x.ApplicationId
	}
	return ""
}

type UpdateAdoptionApplicationStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApplicationId string                 `protobuf:"bytes,1,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	NewStatus     ApplicationStatus      `protobuf:"varint,2,opt,name=new_status,json=newStatus,proto3,enum=adoption.ApplicationStatus" json:"new_status,omitempty"`
	ReviewNotes   string                 `protobuf:"bytes,3,opt,name=review_notes,json=reviewNotes,proto3" json:"review_notes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAdoptionApplicationStatusRequest) Reset() {
	*x = UpdateAdoptionApplicationStatusRequest{}
	mi := &file_adoption_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAdoptionApplicationStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAdoptionApplicationStatusRequest) ProtoMessage() {}

func (x *UpdateAdoptionApplicationStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_adoption_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAdoptionApplicationStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateAdoptionApplicationStatusRequest) Descriptor() ([]byte, []int) {
	return file_adoption_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateAdoptionApplicationStatusRequest) GetApplicationId() string {
	if x != nil {
		return x.ApplicationId
	}
	return ""
}

func (x *UpdateAdoptionApplicationStatusRequest) GetNewStatus() ApplicationStatus {
	if x != nil {
		return x.NewStatus
	}
	return ApplicationStatus_APPLICATION_STATUS_UNSPECIFIED
}

func (x *UpdateAdoptionApplicationStatusRequest) GetReviewNotes() string {
	if x != nil {
		return x.ReviewNotes
	}
	return ""
}

type ListUserAdoptionApplicationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Page          *int32                 `protobuf:"varint,2,opt,name=page,proto3,oneof" json:"page,omitempty"`
	Limit         *int32                 `protobuf:"varint,3,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	StatusFilter  *ApplicationStatus     `protobuf:"varint,4,opt,name=status_filter,json=statusFilter,proto3,enum=adoption.ApplicationStatus,oneof" json:"status_filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserAdoptionApplicationsRequest) Reset() {
	*x = ListUserAdoptionApplicationsRequest{}
	mi := &file_adoption_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserAdoptionApplicationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserAdoptionApplicationsRequest) ProtoMessage() {}

func (x *ListUserAdoptionApplicationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_adoption_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserAdoptionApplicationsRequest.ProtoReflect.Descriptor instead.
func (*ListUserAdoptionApplicationsRequest) Descriptor() ([]byte, []int) {
	return file_adoption_proto_rawDescGZIP(), []int{4}
}

func (x *ListUserAdoptionApplicationsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListUserAdoptionApplicationsRequest) GetPage() int32 {
	if x != nil && x.Page != nil {
		return *x.Page
	}
	return 0
}

func (x *ListUserAdoptionApplicationsRequest) GetLimit() int32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

func (x *ListUserAdoptionApplicationsRequest) GetStatusFilter() ApplicationStatus {
	if x != nil && x.StatusFilter != nil {
		return *x.StatusFilter
	}
	return ApplicationStatus_APPLICATION_STATUS_UNSPECIFIED
}

type ListAdoptionApplicationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Applications  []*AdoptionApplication `protobuf:"bytes,1,rep,name=applications,proto3" json:"applications,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAdoptionApplicationsResponse) Reset() {
	*x = ListAdoptionApplicationsResponse{}
	mi := &file_adoption_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAdoptionApplicationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAdoptionApplicationsResponse) ProtoMessage() {}

func (x *ListAdoptionApplicationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_adoption_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAdoptionApplicationsResponse.ProtoReflect.Descriptor instead.
func (*ListAdoptionApplicationsResponse) Descriptor() ([]byte, []int) {
	return file_adoption_proto_rawDescGZIP(), []int{5}
}

func (x *ListAdoptionApplicationsResponse) GetApplications() []*AdoptionApplication {
	if x != nil {
		return x.Applications
	}
	return nil
}

func (x *ListAdoptionApplicationsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListAdoptionApplicationsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListAdoptionApplicationsResponse) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type AdoptionApplicationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Application   *AdoptionApplication   `protobuf:"bytes,1,opt,name=application,proto3" json:"application,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdoptionApplicationResponse) Reset() {
	*x = AdoptionApplicationResponse{}
	mi := &file_adoption_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdoptionApplicationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdoptionApplicationResponse) ProtoMessage() {}

func (x *AdoptionApplicationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_adoption_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdoptionApplicationResponse.ProtoReflect.Descriptor instead.
func (*AdoptionApplicationResponse) Descriptor() ([]byte, []int) {
	return file_adoption_proto_rawDescGZIP(), []int{6}
}

func (x *AdoptionApplicationResponse) GetApplication() *AdoptionApplication {
	if x != nil {
		return x.Application
	}
	return nil
}

var File_adoption_proto protoreflect.FileDescriptor

const file_adoption_proto_rawDesc = "" +
	"\n" +
	"\x0eadoption.proto\x12\badoption\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd0\x02\n" +
	"\x13AdoptionApplication\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x15\n" +
	"\x06pet_id\x18\x03 \x01(\tR\x05petId\x123\n" +
	"\x06status\x18\x04 \x01(\x0e2\x1b.adoption.ApplicationStatusR\x06status\x12+\n" +
	"\x11application_notes\x18\x05 \x01(\tR\x10applicationNotes\x12!\n" +
	"\freview_notes\x18\x06 \x01(\tR\vreviewNotes\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x7f\n" +
	" CreateAdoptionApplicationRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x15\n" +
	"\x06pet_id\x18\x02 \x01(\tR\x05petId\x12+\n" +
	"\x11application_notes\x18\x03 \x01(\tR\x10applicationNotes\"F\n" +
	"\x1dGetAdoptionApplicationRequest\x12%\n" +
	"\x0eapplication_id\x18\x01 \x01(\tR\rapplicationId\"\xae\x01\n" +
	"&UpdateAdoptionApplicationStatusRequest\x12%\n" +
	"\x0eapplication_id\x18\x01 \x01(\tR\rapplicationId\x12:\n" +
	"\n" +
	"new_status\x18\x02 \x01(\x0e2\x1b.adoption.ApplicationStatusR\tnewStatus\x12!\n" +
	"\freview_notes\x18\x03 \x01(\tR\vreviewNotes\"\xde\x01\n" +
	"#ListUserAdoptionApplicationsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x17\n" +
	"\x04page\x18\x02 \x01(\x05H\x00R\x04page\x88\x01\x01\x12\x19\n" +
	"\x05limit\x18\x03 \x01(\x05H\x01R\x05limit\x88\x01\x01\x12E\n" +
	"\rstatus_filter\x18\x04 \x01(\x0e2\x1b.adoption.ApplicationStatusH\x02R\fstatusFilter\x88\x01\x01B\a\n" +
	"\x05_pageB\b\n" +
	"\x06_limitB\x10\n" +
	"\x0e_status_filter\"\xb0\x01\n" +
	" ListAdoptionApplicationsResponse\x12A\n" +
	"\fapplications\x18\x01 \x03(\v2\x1d.adoption.AdoptionApplicationR\fapplications\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"^\n" +
	"\x1bAdoptionApplicationResponse\x12?\n" +
	"\vapplication\x18\x01 \x01(\v2\x1d.adoption.AdoptionApplicationR\vapplication*~\n" +
	"\x11ApplicationStatus\x12\"\n" +
	"\x1eAPPLICATION_STATUS_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0ePENDING_REVIEW\x10\x01\x12\f\n" +
	"\bAPPROVED\x10\x02\x12\f\n" +
	"\bREJECTED\x10\x03\x12\x15\n" +
	"\x11CANCELLED_BY_USER\x10\x052\xe2\x03\n" +
	"\x0fAdoptionService\x12n\n" +
	"\x19CreateAdoptionApplication\x12*.adoption.CreateAdoptionApplicationRequest\x1a%.adoption.AdoptionApplicationResponse\x12h\n" +
	"\x16GetAdoptionApplication\x12'.adoption.GetAdoptionApplicationRequest\x1a%.adoption.AdoptionApplicationResponse\x12z\n" +
	"\x1fUpdateAdoptionApplicationStatus\x120.adoption.UpdateAdoptionApplicationStatusRequest\x1a%.adoption.AdoptionApplicationResponse\x12y\n" +
	"\x1cListUserAdoptionApplications\x12-.adoption.ListUserAdoptionApplicationsRequest\x1a*.adoption.ListAdoptionApplicationsResponseBBZ@github.com/zhandarbeks/petstore-final-project/genprotos/adoptionb\x06proto3"

var (
	file_adoption_proto_rawDescOnce sync.Once
	file_adoption_proto_rawDescData []byte
)

func file_adoption_proto_rawDescGZIP() []byte {
	file_adoption_proto_rawDescOnce.Do(func() {
		file_adoption_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_adoption_proto_rawDesc), len(file_adoption_proto_rawDesc)))
	})
	return file_adoption_proto_rawDescData
}

var file_adoption_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_adoption_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_adoption_proto_goTypes = []any{
	(ApplicationStatus)(0),                         // 0: adoption.ApplicationStatus
	(*AdoptionApplication)(nil),                    // 1: adoption.AdoptionApplication
	(*CreateAdoptionApplicationRequest)(nil),       // 2: adoption.CreateAdoptionApplicationRequest
	(*GetAdoptionApplicationRequest)(nil),          // 3: adoption.GetAdoptionApplicationRequest
	(*UpdateAdoptionApplicationStatusRequest)(nil), // 4: adoption.UpdateAdoptionApplicationStatusRequest
	(*ListUserAdoptionApplicationsRequest)(nil),    // 5: adoption.ListUserAdoptionApplicationsRequest
	(*ListAdoptionApplicationsResponse)(nil),       // 6: adoption.ListAdoptionApplicationsResponse
	(*AdoptionApplicationResponse)(nil),            // 7: adoption.AdoptionApplicationResponse
	(*timestamppb.Timestamp)(nil),                  // 8: google.protobuf.Timestamp
}
var file_adoption_proto_depIdxs = []int32{
	0,  // 0: adoption.AdoptionApplication.status:type_name -> adoption.ApplicationStatus
	8,  // 1: adoption.AdoptionApplication.created_at:type_name -> google.protobuf.Timestamp
	8,  // 2: adoption.AdoptionApplication.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 3: adoption.UpdateAdoptionApplicationStatusRequest.new_status:type_name -> adoption.ApplicationStatus
	0,  // 4: adoption.ListUserAdoptionApplicationsRequest.status_filter:type_name -> adoption.ApplicationStatus
	1,  // 5: adoption.ListAdoptionApplicationsResponse.applications:type_name -> adoption.AdoptionApplication
	1,  // 6: adoption.AdoptionApplicationResponse.application:type_name -> adoption.AdoptionApplication
	2,  // 7: adoption.AdoptionService.CreateAdoptionApplication:input_type -> adoption.CreateAdoptionApplicationRequest
	3,  // 8: adoption.AdoptionService.GetAdoptionApplication:input_type -> adoption.GetAdoptionApplicationRequest
	4,  // 9: adoption.AdoptionService.UpdateAdoptionApplicationStatus:input_type -> adoption.UpdateAdoptionApplicationStatusRequest
	5,  // 10: adoption.AdoptionService.ListUserAdoptionApplications:input_type -> adoption.ListUserAdoptionApplicationsRequest
	7,  // 11: adoption.AdoptionService.CreateAdoptionApplication:output_type -> adoption.AdoptionApplicationResponse
	7,  // 12: adoption.AdoptionService.GetAdoptionApplication:output_type -> adoption.AdoptionApplicationResponse
	7,  // 13: adoption.AdoptionService.UpdateAdoptionApplicationStatus:output_type -> adoption.AdoptionApplicationResponse
	6,  // 14: adoption.AdoptionService.ListUserAdoptionApplications:output_type -> adoption.ListAdoptionApplicationsResponse
	11, // [11:15] is the sub-list for method output_type
	7,  // [7:11] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_adoption_proto_init() }
func file_adoption_proto_init() {
	if File_adoption_proto != nil {
		return
	}
	file_adoption_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_adoption_proto_rawDesc), len(file_adoption_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_adoption_proto_goTypes,
		DependencyIndexes: file_adoption_proto_depIdxs,
		EnumInfos:         file_adoption_proto_enumTypes,
		MessageInfos:      file_adoption_proto_msgTypes,
	}.Build()
	File_adoption_proto = out.File
	file_adoption_proto_goTypes = nil
	file_adoption_proto_depIdxs = nil
}
