// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: pet.proto

package pet

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AdoptionStatus int32

const (
	AdoptionStatus_ADOPTION_STATUS_UNSPECIFIED AdoptionStatus = 0
	AdoptionStatus_AVAILABLE                   AdoptionStatus = 1
	AdoptionStatus_PENDING_ADOPTION            AdoptionStatus = 2
	AdoptionStatus_ADOPTED                     AdoptionStatus = 3
)

// Enum value maps for AdoptionStatus.
var (
	AdoptionStatus_name = map[int32]string{
		0: "ADOPTION_STATUS_UNSPECIFIED",
		1: "AVAILABLE",
		2: "PENDING_ADOPTION",
		3: "ADOPTED",
	}
	AdoptionStatus_value = map[string]int32{
		"ADOPTION_STATUS_UNSPECIFIED": 0,
		"AVAILABLE":                   1,
		"PENDING_ADOPTION":            2,
		"ADOPTED":                     3,
	}
)

func (x AdoptionStatus) Enum() *AdoptionStatus {
	p := new(AdoptionStatus)
	*p = x
	return p
}

func (x AdoptionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AdoptionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_pet_proto_enumTypes[0].Descriptor()
}

func (AdoptionStatus) Type() protoreflect.EnumType {
	return &file_pet_proto_enumTypes[0]
}

func (x AdoptionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AdoptionStatus.Descriptor instead.
func (AdoptionStatus) EnumDescriptor() ([]byte, []int) {
	return file_pet_proto_rawDescGZIP(), []int{0}
}

type Pet struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Species         string                 `protobuf:"bytes,3,opt,name=species,proto3" json:"species,omitempty"`
	Breed           string                 `protobuf:"bytes,4,opt,name=breed,proto3" json:"breed,omitempty"`
	Age             int32                  `protobuf:"varint,5,opt,name=age,proto3" json:"age,omitempty"`
	Description     string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	AdoptionStatus  AdoptionStatus         `protobuf:"varint,7,opt,name=adoption_status,json=adoptionStatus,proto3,enum=pet.AdoptionStatus" json:"adoption_status,omitempty"`
	ListedByUserId  string                 `protobuf:"bytes,8,opt,name=listed_by_user_id,json=listedByUserId,proto3" json:"listed_by_user_id,omitempty"`
	AdoptedByUserId string                 `protobuf:"bytes,9,opt,name=adopted_by_user_id,json=adoptedByUserId,proto3" json:"adopted_by_user_id,omitempty"`
	CreatedAt       string                 `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       string                 `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	ImageUrls       []string               `protobuf:"bytes,12,rep,name=image_urls,json=imageUrls,proto3" json:"image_urls,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Pet) Reset() {
	*x = Pet{}
	mi := &file_pet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pet) ProtoMessage() {}

func (x *Pet) ProtoReflect() protoreflect.Message {
	mi := &file_pet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pet.ProtoReflect.Descriptor instead.
func (*Pet) Descriptor() ([]byte, []int) {
	return file_pet_proto_rawDescGZIP(), []int{0}
}

func (x *Pet) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Pet) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Pet) GetSpecies() string {
	if x != nil {
		return x.Species
	}
	return ""
}

func (x *Pet) GetBreed() string {
	if x != nil {
		return x.Breed
	}
	return ""
}

func (x *Pet) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *Pet) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Pet) GetAdoptionStatus() AdoptionStatus {
	if x != nil {
		return x.AdoptionStatus
	}
	return AdoptionStatus_ADOPTION_STATUS_UNSPECIFIED
}

func (x *Pet) GetListedByUserId() string {
	if x != nil {
		return x.ListedByUserId
	}
	return ""
}

func (x *Pet) GetAdoptedByUserId() string {
	if x != nil {
		return x.AdoptedByUserId
	}
	return ""
}

func (x *Pet) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Pet) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Pet) GetImageUrls() []string {
	if x != nil {
		return x.ImageUrls
	}
	return nil
}

type CreatePetRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Species        string                 `protobuf:"bytes,2,opt,name=species,proto3" json:"species,omitempty"`
	Breed          string                 `protobuf:"bytes,3,opt,name=breed,proto3" json:"breed,omitempty"`
	Age            int32                  `protobuf:"varint,4,opt,name=age,proto3" json:"age,omitempty"`
	Description    string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	ListedByUserId string                 `protobuf:"bytes,6,opt,name=listed_by_user_id,json=listedByUserId,proto3" json:"listed_by_user_id,omitempty"`
	ImageUrls      []string               `protobuf:"bytes,7,rep,name=image_urls,json=imageUrls,proto3" json:"image_urls,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreatePetRequest) Reset() {
	*x = CreatePetRequest{}
	mi := &file_pet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePetRequest) ProtoMessage() {}

func (x *CreatePetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePetRequest.ProtoReflect.Descriptor instead.
func (*CreatePetRequest) Descriptor() ([]byte, []int) {
	return file_pet_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePetRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreatePetRequest) GetSpecies() string {
	if x != nil {
		return x.Species
	}
	return ""
}

func (x *CreatePetRequest) GetBreed() string {
	if x != nil {
		return x.Breed
	}
	return ""
}

func (x *CreatePetRequest) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *CreatePetRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreatePetRequest) GetListedByUserId() string {
	if x != nil {
		return x.ListedByUserId
	}
	return ""
}

func (x *CreatePetRequest) GetImageUrls() []string {
	if x != nil {
		return x.ImageUrls
	}
	return nil
}

type GetPetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PetId         string                 `protobuf:"bytes,1,opt,name=pet_id,json=petId,proto3" json:"pet_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPetRequest) Reset() {
	*x = GetPetRequest{}
	mi := &file_pet_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPetRequest) ProtoMessage() {}

func (x *GetPetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pet_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPetRequest.ProtoReflect.Descriptor instead.
func (*GetPetRequest) Descriptor() ([]byte, []int) {
	return file_pet_proto_rawDescGZIP(), []int{2}
}

func (x *GetPetRequest) GetPetId() string {
	if x != nil {
		return x.PetId
	}
	return ""
}

type UpdatePetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PetId         string                 `protobuf:"bytes,1,opt,name=pet_id,json=petId,proto3" json:"pet_id,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Species       *string                `protobuf:"bytes,3,opt,name=species,proto3,oneof" json:"species,omitempty"`
	Breed         *string                `protobuf:"bytes,4,opt,name=breed,proto3,oneof" json:"breed,omitempty"`
	Age           *int32                 `protobuf:"varint,5,opt,name=age,proto3,oneof" json:"age,omitempty"`
	Description   *string                `protobuf:"bytes,6,opt,name=description,proto3,oneof" json:"description,omitempty"`
	ImageUrls     []string               `protobuf:"bytes,7,rep,name=image_urls,json=imageUrls,proto3" json:"image_urls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePetRequest) Reset() {
	*x = UpdatePetRequest{}
	mi := &file_pet_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePetRequest) ProtoMessage() {}

func (x *UpdatePetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pet_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePetRequest.ProtoReflect.Descriptor instead.
func (*UpdatePetRequest) Descriptor() ([]byte, []int) {
	return file_pet_proto_rawDescGZIP(), []int{3}
}

func (x *UpdatePetRequest) GetPetId() string {
	if x != nil {
		return x.PetId
	}
	return ""
}

func (x *UpdatePetRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdatePetRequest) GetSpecies() string {
	if x != nil && x.Species != nil {
		return *x.Species
	}
	return ""
}

func (x *UpdatePetRequest) GetBreed() string {
	if x != nil && x.Breed != nil {
		return *x.Breed
	}
	return ""
}

func (x *UpdatePetRequest) GetAge() int32 {
	if x != nil && x.Age != nil {
		return *x.Age
	}
	return 0
}

func (x *UpdatePetRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *UpdatePetRequest) GetImageUrls() []string {
	if x != nil {
		return x.ImageUrls
	}
	return nil
}

type DeletePetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PetId         string                 `protobuf:"bytes,1,opt,name=pet_id,json=petId,proto3" json:"pet_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePetRequest) Reset() {
	*x = DeletePetRequest{}
	mi := &file_pet_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePetRequest) ProtoMessage() {}

func (x *DeletePetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pet_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePetRequest.ProtoReflect.Descriptor instead.
func (*DeletePetRequest) Descriptor() ([]byte, []int) {
	return file_pet_proto_rawDescGZIP(), []int{4}
}

func (x *DeletePetRequest) GetPetId() string {
	if x != nil {
		return x.PetId
	}
	return ""
}

type ListPetsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          *int32                 `protobuf:"varint,1,opt,name=page,proto3,oneof" json:"page,omitempty"`
	Limit         *int32                 `protobuf:"varint,2,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	SpeciesFilter *string                `protobuf:"bytes,3,opt,name=species_filter,json=speciesFilter,proto3,oneof" json:"species_filter,omitempty"`
	StatusFilter  *AdoptionStatus        `protobuf:"varint,4,opt,name=status_filter,json=statusFilter,proto3,enum=pet.AdoptionStatus,oneof" json:"status_filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPetsRequest) Reset() {
	*x = ListPetsRequest{}
	mi := &file_pet_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPetsRequest) ProtoMessage() {}

func (x *ListPetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pet_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPetsRequest.ProtoReflect.Descriptor instead.
func (*ListPetsRequest) Descriptor() ([]byte, []int) {
	return file_pet_proto_rawDescGZIP(), []int{5}
}

func (x *ListPetsRequest) GetPage() int32 {
	if x != nil && x.Page != nil {
		return *x.Page
	}
	return 0
}

func (x *ListPetsRequest) GetLimit() int32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

func (x *ListPetsRequest) GetSpeciesFilter() string {
	if x != nil && x.SpeciesFilter != nil {
		return *x.SpeciesFilter
	}
	return ""
}

func (x *ListPetsRequest) GetStatusFilter() AdoptionStatus {
	if x != nil && x.StatusFilter != nil {
		return *x.StatusFilter
	}
	return AdoptionStatus_ADOPTION_STATUS_UNSPECIFIED
}

type ListPetsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pets          []*Pet                 `protobuf:"bytes,1,rep,name=pets,proto3" json:"pets,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPetsResponse) Reset() {
	*x = ListPetsResponse{}
	mi := &file_pet_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPetsResponse) ProtoMessage() {}

func (x *ListPetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pet_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPetsResponse.ProtoReflect.Descriptor instead.
func (*ListPetsResponse) Descriptor() ([]byte, []int) {
	return file_pet_proto_rawDescGZIP(), []int{6}
}

func (x *ListPetsResponse) GetPets() []*Pet {
	if x != nil {
		return x.Pets
	}
	return nil
}

func (x *ListPetsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListPetsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListPetsResponse) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type UpdatePetAdoptionStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PetId         string                 `protobuf:"bytes,1,opt,name=pet_id,json=petId,proto3" json:"pet_id,omitempty"`
	NewStatus     AdoptionStatus         `protobuf:"varint,2,opt,name=new_status,json=newStatus,proto3,enum=pet.AdoptionStatus" json:"new_status,omitempty"`
	AdopterUserId string                 `protobuf:"bytes,3,opt,name=adopter_user_id,json=adopterUserId,proto3" json:"adopter_user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePetAdoptionStatusRequest) Reset() {
	*x = UpdatePetAdoptionStatusRequest{}
	mi := &file_pet_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePetAdoptionStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePetAdoptionStatusRequest) ProtoMessage() {}

func (x *UpdatePetAdoptionStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pet_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePetAdoptionStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdatePetAdoptionStatusRequest) Descriptor() ([]byte, []int) {
	return file_pet_proto_rawDescGZIP(), []int{7}
}

func (x *UpdatePetAdoptionStatusRequest) GetPetId() string {
	if x != nil {
		return x.PetId
	}
	return ""
}

func (x *UpdatePetAdoptionStatusRequest) GetNewStatus() AdoptionStatus {
	if x != nil {
		return x.NewStatus
	}
	return AdoptionStatus_ADOPTION_STATUS_UNSPECIFIED
}

func (x *UpdatePetAdoptionStatusRequest) GetAdopterUserId() string {
	if x != nil {
		return x.AdopterUserId
	}
	return ""
}

type PetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pet           *Pet                   `protobuf:"bytes,1,opt,name=pet,proto3" json:"pet,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PetResponse) Reset() {
	*x = PetResponse{}
	mi := &file_pet_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PetResponse) ProtoMessage() {}

func (x *PetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pet_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PetResponse.ProtoReflect.Descriptor instead.
func (*PetResponse) Descriptor() ([]byte, []int) {
	return file_pet_proto_rawDescGZIP(), []int{8}
}

func (x *PetResponse) GetPet() *Pet {
	if x != nil {
		return x.Pet
	}
	return nil
}

type EmptyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyResponse) Reset() {
	*x = EmptyResponse{}
	mi := &file_pet_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyResponse) ProtoMessage() {}

func (x *EmptyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pet_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyResponse.ProtoReflect.Descriptor instead.
func (*EmptyResponse) Descriptor() ([]byte, []int) {
	return file_pet_proto_rawDescGZIP(), []int{9}
}

var File_pet_proto protoreflect.FileDescriptor

const file_pet_proto_rawDesc = "" +
	"\n" +
	"\tpet.proto\x12\x03pet\"\x80\x03\n" +
	"\x03Pet\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aspecies\x18\x03 \x01(\tR\aspecies\x12\x14\n" +
	"\x05breed\x18\x04 \x01(\tR\x05breed\x12\x10\n" +
	"\x03age\x18\x05 \x01(\x05R\x03age\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12<\n" +
	"\x0fadoption_status\x18\a \x01(\x0e2\x13.pet.AdoptionStatusR\x0eadoptionStatus\x12)\n" +
	"\x11listed_by_user_id\x18\b \x01(\tR\x0elistedByUserId\x12+\n" +
	"\x12adopted_by_user_id\x18\t \x01(\tR\x0fadoptedByUserId\x12\x1d\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\v \x01(\tR\tupdatedAt\x12\x1d\n" +
	"\n" +
	"image_urls\x18\f \x03(\tR\timageUrls\"\xd4\x01\n" +
	"\x10CreatePetRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aspecies\x18\x02 \x01(\tR\aspecies\x12\x14\n" +
	"\x05breed\x18\x03 \x01(\tR\x05breed\x12\x10\n" +
	"\x03age\x18\x04 \x01(\x05R\x03age\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12)\n" +
	"\x11listed_by_user_id\x18\x06 \x01(\tR\x0elistedByUserId\x12\x1d\n" +
	"\n" +
	"image_urls\x18\a \x03(\tR\timageUrls\"&\n" +
	"\rGetPetRequest\x12\x15\n" +
	"\x06pet_id\x18\x01 \x01(\tR\x05petId\"\x90\x02\n" +
	"\x10UpdatePetRequest\x12\x15\n" +
	"\x06pet_id\x18\x01 \x01(\tR\x05petId\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01\x12\x1d\n" +
	"\aspecies\x18\x03 \x01(\tH\x01R\aspecies\x88\x01\x01\x12\x19\n" +
	"\x05breed\x18\x04 \x01(\tH\x02R\x05breed\x88\x01\x01\x12\x15\n" +
	"\x03age\x18\x05 \x01(\x05H\x03R\x03age\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x06 \x01(\tH\x04R\vdescription\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"image_urls\x18\a \x03(\tR\timageUrlsB\a\n" +
	"\x05_nameB\n" +
	"\n" +
	"\b_speciesB\b\n" +
	"\x06_breedB\x06\n" +
	"\x04_ageB\x0e\n" +
	"\f_description\")\n" +
	"\x10DeletePetRequest\x12\x15\n" +
	"\x06pet_id\x18\x01 \x01(\tR\x05petId\"\xe8\x01\n" +
	"\x0fListPetsRequest\x12\x17\n" +
	"\x04page\x18\x01 \x01(\x05H\x00R\x04page\x88\x01\x01\x12\x19\n" +
	"\x05limit\x18\x02 \x01(\x05H\x01R\x05limit\x88\x01\x01\x12*\n" +
	"\x0especies_filter\x18\x03 \x01(\tH\x02R\rspeciesFilter\x88\x01\x01\x12=\n" +
	"\rstatus_filter\x18\x04 \x01(\x0e2\x13.pet.AdoptionStatusH\x03R\fstatusFilter\x88\x01\x01B\a\n" +
	"\x05_pageB\b\n" +
	"\x06_limitB\x11\n" +
	"\x0f_species_filterB\x10\n" +
	"\x0e_status_filter\"{\n" +
	"\x10ListPetsResponse\x12\x1c\n" +
	"\x04pets\x18\x01 \x03(\v2\b.pet.PetR\x04pets\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"\x93\x01\n" +
	"\x1eUpdatePetAdoptionStatusRequest\x12\x15\n" +
	"\x06pet_id\x18\x01 \x01(\tR\x05petId\x122\n" +
	"\n" +
	"new_status\x18\x02 \x01(\x0e2\x13.pet.AdoptionStatusR\tnewStatus\x12&\n" +
	"\x0fadopter_user_id\x18\x03 \x01(\tR\radopterUserId\")\n" +
	"\vPetResponse\x12\x1a\n" +
	"\x03pet\x18\x01 \x01(\v2\b.pet.PetR\x03pet\"\x0f\n" +
	"\rEmptyResponse*c\n" +
	"\x0eAdoptionStatus\x12\x1f\n" +
	"\x1bADOPTION_STATUS_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tAVAILABLE\x10\x01\x12\x14\n" +
	"\x10PENDING_ADOPTION\x10\x02\x12\v\n" +
	"\aADOPTED\x10\x032\xeb\x02\n" +
	"\n" +
	"PetService\x124\n" +
	"\tCreatePet\x12\x15.pet.CreatePetRequest\x1a\x10.pet.PetResponse\x12.\n" +
	"\x06GetPet\x12\x12.pet.GetPetRequest\x1a\x10.pet.PetResponse\x124\n" +
	"\tUpdatePet\x12\x15.pet.UpdatePetRequest\x1a\x10.pet.PetResponse\x126\n" +
	"\tDeletePet\x12\x15.pet.DeletePetRequest\x1a\x12.pet.EmptyResponse\x127\n" +
	"\bListPets\x12\x14.pet.ListPetsRequest\x1a\x15.pet.ListPetsResponse\x12P\n" +
	"\x17UpdatePetAdoptionStatus\x12#.pet.UpdatePetAdoptionStatusRequest\x1a\x10.pet.PetResponseB=Z;github.com/zhandarbeks/petstore-final-project/genprotos/petb\x06proto3"

var (
	file_pet_proto_rawDescOnce sync.Once
	file_pet_proto_rawDescData []byte
)

func file_pet_proto_rawDescGZIP() []byte {
	file_pet_proto_rawDescOnce.Do(func() {
		file_pet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pet_proto_rawDesc), len(file_pet_proto_rawDesc)))
	})
	return file_pet_proto_rawDescData
}

var file_pet_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pet_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_pet_proto_goTypes = []any{
	(AdoptionStatus)(0),                    // 0: pet.AdoptionStatus
	(*Pet)(nil),                            // 1: pet.Pet
	(*CreatePetRequest)(nil),               // 2: pet.CreatePetRequest
	(*GetPetRequest)(nil),                  // 3: pet.GetPetRequest
	(*UpdatePetRequest)(nil),               // 4: pet.UpdatePetRequest
	(*DeletePetRequest)(nil),               // 5: pet.DeletePetRequest
	(*ListPetsRequest)(nil),                // 6: pet.ListPetsRequest
	(*ListPetsResponse)(nil),               // 7: pet.ListPetsResponse
	(*UpdatePetAdoptionStatusRequest)(nil), // 8: pet.UpdatePetAdoptionStatusRequest
	(*PetResponse)(nil),                    // 9: pet.PetResponse
	(*EmptyResponse)(nil),                  // 10: pet.EmptyResponse
}
var file_pet_proto_depIdxs = []int32{
	0,  // 0: pet.Pet.adoption_status:type_name -> pet.AdoptionStatus
	0,  // 1: pet.ListPetsRequest.status_filter:type_name -> pet.AdoptionStatus
	1,  // 2: pet.ListPetsResponse.pets:type_name -> pet.Pet
	0,  // 3: pet.UpdatePetAdoptionStatusRequest.new_status:type_name -> pet.AdoptionStatus
	1,  // 4: pet.PetResponse.pet:type_name -> pet.Pet
	2,  // 5: pet.PetService.CreatePet:input_type -> pet.CreatePetRequest
	3,  // 6: pet.PetService.GetPet:input_type -> pet.GetPetRequest
	4,  // 7: pet.PetService.UpdatePet:input_type -> pet.UpdatePetRequest
	5,  // 8: pet.PetService.DeletePet:input_type -> pet.DeletePetRequest
	6,  // 9: pet.PetService.ListPets:input_type -> pet.ListPetsRequest
	8,  // 10: pet.PetService.UpdatePetAdoptionStatus:input_type -> pet.UpdatePetAdoptionStatusRequest
	9,  // 11: pet.PetService.CreatePet:output_type -> pet.PetResponse
	9,  // 12: pet.PetService.GetPet:output_type -> pet.PetResponse
	9,  // 13: pet.PetService.UpdatePet:output_type -> pet.PetResponse
	10, // 14: pet.PetService.DeletePet:output_type -> pet.EmptyResponse
	7,  // 15: pet.PetService.ListPets:output_type -> pet.ListPetsResponse
	9,  // 16: pet.PetService.UpdatePetAdoptionStatus:output_type -> pet.PetResponse
	11, // [11:17] is the sub-list for method output_type
	5,  // [5:11] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_pet_proto_init() }
func file_pet_proto_init() {
	if File_pet_proto != nil {
		return
	}
	file_pet_proto_msgTypes[3].OneofWrappers = []any{}
	file_pet_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pet_proto_rawDesc), len(file_pet_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pet_proto_goTypes,
		DependencyIndexes: file_pet_proto_depIdxs,
		EnumInfos:         file_pet_proto_enumTypes,
		MessageInfos:      file_pet_proto_msgTypes,
	}.Build()
	File_pet_proto = out.File
	file_pet_proto_goTypes = nil
	file_pet_proto_depIdxs = nil
}
